---
version: "3"
services:
 devopsdb:
   image: ramkishore9/poc:imagedb
   ports:
     - "3306:3306"

 application:
   image: ramkishore9/poc:imageapp
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
